const guides=[
 {title:"Choose a safe, matched system",intro:"Start with the smallest motor and battery combination that meets your actual water conditions. Matching components now prevents expensive rework later.",heading:"Decide these three things",items:["Freshwater or saltwater use","Desired runtime and backup paddling range","A mounting location that keeps the kayak balanced"],tip:"Beginner tip: Buy the motor, battery, controller, and connectors as one compatible system when possible.",diagram:["Solar panel","Charge controller","Battery + motor"]},
 {title:"Gather parts and tools",intro:"Put every component in one place before drilling, cutting, or mounting anything. Check off physical items—not items still in an online cart.",heading:"Core checklist",items:["Marine-rated motor and mount","LiFePO₄ battery with matched charger","Flexible solar panel and controller","Marine wire, fuse, connectors, and sealant","Life jacket, paddle, and emergency cutoff"],tip:"Stop point: If voltage, connector type, or fuse sizing is unclear, do not connect the battery yet.",diagram:["Parts verified","Tools ready","Build area clear"]},
 {title:"Bench-test before mounting",intro:"Test the electrical system on a dry workbench so troubleshooting stays simple and the kayak remains untouched.",heading:"Safe test order",items:["Keep the propeller removed or fully clear","Install the correctly sized fuse near the battery","Verify polarity before connecting","Run the motor briefly at low speed","Disconnect power before making adjustments"],tip:"Success looks like: smooth motor response, cool wiring, and no warning lights or unusual odor.",diagram:["Fuse first","Check polarity","Low-speed test"]},
 {title:"Mount, seal, and water-test",intro:"Install the mount without weakening the hull, secure every cable, then test close to shore in calm conditions.",heading:"Finish in this order",items:["Dry-fit the mount and confirm paddle clearance","Use backing plates where the hull needs support","Seal every drilled opening with marine sealant","Secure battery weight low and centered","Complete a short shore-tethered water test"],tip:"Do not rely on the motor as your only way home. Carry a usable paddle and plan for reduced battery performance.",diagram:["Dry fit","Seal + secure","Shore test"]}
];
let current=0;
const content=document.querySelector('#guideContent');
function renderStep(){const g=guides[current];content.innerHTML=`<h3>${g.title}</h3><p>${g.intro}</p><h4>${g.heading}</h4><ul class="plain-list">${g.items.map(x=>`<li>${x}</li>`).join('')}</ul><div class="diagram" aria-label="Simple process diagram">${g.diagram.map(x=>`<div>${x}</div>`).join('')}</div><div class="tip"><strong>${g.tip.split(':')[0]}:</strong>${g.tip.includes(':')?g.tip.slice(g.tip.indexOf(':')+1):g.tip}</div>`;document.querySelector('#stepLabel').textContent=`STEP ${current+1} OF 4`;document.querySelector('.progress-head span:last-child').textContent=`${(current+1)*25}% complete`;document.querySelector('.progress i').style.width=`${(current+1)*25}%`;document.querySelectorAll('.step').forEach((b,i)=>b.classList.toggle('active',i===current));document.querySelector('#backStep').disabled=current===0;document.querySelector('#nextStep').textContent=current===3?'Finish example ✓':'Mark done & continue →'}
document.querySelectorAll('.step').forEach((b,i)=>b.addEventListener('click',()=>{current=i;renderStep()}));
document.querySelector('#nextStep').addEventListener('click',()=>{if(current<3){current++;renderStep()}else{document.querySelector('#tiers').scrollIntoView({behavior:'smooth'})}});
document.querySelector('#backStep').addEventListener('click',()=>{if(current>0){current--;renderStep()}});
document.querySelector('#projectForm').addEventListener('submit',e=>{e.preventDefault();const project=document.querySelector('#project').value.trim();const zip=document.querySelector('#zip').value;document.querySelector('#generatedTitle').textContent=project;document.querySelector('#generatedMeta').textContent=`Complete beginner · ZIP ${zip} · Free starter framework`;document.querySelector('#generated').classList.remove('hidden');document.querySelector('#generated').scrollIntoView({behavior:'smooth',block:'center'})});
document.querySelector('#themeToggle').addEventListener('click',()=>document.body.classList.toggle('dark'));
document.querySelectorAll('.tier-select').forEach(button=>button.addEventListener('click',()=>{const card=button.closest('.tier');const level=Number(card.dataset.tier);document.querySelectorAll('.tier').forEach(x=>x.classList.remove('selected'));card.classList.add('selected');document.querySelector('#selectedTier').textContent=card.querySelector('.tier-name').textContent;document.querySelector('#specialists').scrollIntoView({behavior:'smooth'});const note=document.querySelector('#specialtyChoice');if(level<3){note.classList.remove('hidden');note.textContent='Specialty agents begin at the Senior level. Intern and Mid-Level remain available for focused general help.'}else note.classList.add('hidden')}));
document.querySelectorAll('.specialty-grid button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.specialty-grid button').forEach(x=>x.classList.remove('chosen'));button.classList.add('chosen');const name=button.querySelector('strong').textContent;const tier=document.querySelector('#selectedTier').textContent;const note=document.querySelector('#specialtyChoice');note.textContent=`${tier} · ${name} selected. This combination will be added to the project setup flow in the next build stage.`;note.classList.remove('hidden')}));
renderStep();
